; CAMERON BINIAMOW
; ECEN 3320
; LAB 2.2.2: PACKED BCD TO ASCII
; DUE: 10/09/2020

;----------------------------------------------------------------
; MAIN

		ORG	0H
		MOV	DPTR, #MYDATA		; LOAD ROM POINTER
		MOV	R3, #4			; DATA LENGTH
		MOV	R0, #50H		; LOAD RAM POINTER

L0:		ACALL	ASCII			; CONVERT PACKED BCD TO ASCII
		ACALL	STORE_RAM		; STORE ASCII DATA IN RAM
		DJNZ	R3, L0			; LOOP UNTIL ALL DATA IS ASCII & STORED IN RAM
HERE:		SJMP	HERE			; STAY HERE

;----------------------------------------------------------------
; UNPACKS BCD STORED IN ROM
; CONVERTS TO ASCII

ASCII:
		CLR	A			; CLEAR ACCUMULATOR
		MOVC	A, @A + DPTR		; MOVE DATA FROM CODE SPACE
		MOV	R4, A			; COPY PACKED BCD TO CONVERT LOWER NIBBLE
		ANL	A, #0F0H		; MASK UPPER NIBBLE - XXXX 0000
		SWAP	A			; XXXX 0000 => 0000 XXXX
		ORL	A, #30H		; CONVERT TO ASCII - 0011 XXXX
		MOV	B, A			; A => B
		MOV	A, R4			; LOAD ORIGINAL PACKED BCD VALUE
		ANL	A, #0FH		; MASK LOWER NIBBLE - 0000 YYYY
		ORL	A, #30H		; CONVERT TO ASCII - 0011 YYYY
		INC	DPTR			; INCREMENT ROM POINTER		
		RET

;----------------------------------------------------------------
; STORES DATA IN RAM

STORE_RAM:
		MOV	@R0, B			; SAVE UPPER NIBBLE IN RAM
		INC	R0			; INCREMENT RAM POINTER
		MOV	@R0, A			; SAVE LOWER NIBBLE IN RAM
		INC	R0			; INCREMENT RAM POINTER
		RET

;----------------------------------------------------------------
; DATA

		ORG	150H
MYDATA:	DB	28H,13H,36H,79H

		END
